default:
  report_index:
    - v0
    - icf
    - ento
    - anomalies-detection
    - safety-efficacy
    - pharmacy
    - anomalies
    - lab
    - monitoring
    - monitoring-issues-ui
  invalidation_endpoint: "/*"
endpoint_issues_ui:
  report_index:
    - monitoring-issues-ui
  invalidation_endpoint: "/monitoring-issues-ui/*"
