default:
  report_index:
    - safety-efficacy
develop:
  report_index:
    - v0
    - icf
    - ento
    - anomalies-detection
    - safety-efficacy
    - pharmacy
    - anomalies
    - lab
    - monitoring
