project:
  type: website

website:
  title: "BOHEMIA Kenya trial"
  sidebar:
    background: "firebrick"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: Distance analyses
        contents: distance_analyses/*
      - section: Prevalence and incidence
        contents: prevalence_incidence/*
    tools:
      - icon: github
        menu:
          - text: Code
            url: https://github.com/mbrudd/kenya

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
